# NumPy Basics: Arrays and Vectorized Computation

In [7]:
import numpy as np
np.__version__

'1.18.1'

In [8]:
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=False)

In [9]:
y = np.array([1.5e-10,1.5,1500])
print(y)
np.set_printoptions(suppress=True)
print(y)

[1.5e-10 1.5e+00 1.5e+03]
[   0.     1.5 1500. ]


In [10]:
import numpy as np
my_arr = np.arange(100000)
my_list = list(range(100000))

In [11]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 2 ms


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 173 ms


## The NumPy ndarray: A Multidimensional Array Object

In [13]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [14]:
data * 10

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

In [15]:
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

### Creating ndarrays

In [18]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[1.0678e-311, 3.1620e-322],
        [0.0000e+000, 0.0000e+000],
        [0.0000e+000, 3.3510e-033]],

       [[1.0017e+165, 2.3174e-052],
        [6.1660e-042, 9.5990e-071],
        [2.7263e-056, 2.0400e+160]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [30]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [31]:
float_arr.dtype

dtype('float64')

In [32]:
arr

array([1, 2, 3, 4, 5])

In [33]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42f'], dtype=np.string_)
numeric_strings.astype(float)

ValueError: could not convert string to float: '42f'

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)dtype 객체


In [ ]:
empty_data = np.empty(8)
empty_data

In [ ]:
empty_uint32 = np.empty(8, dtype='u4') #unsiged 4bytes
empty_uint32

### Arithmetic with NumPy Arrays

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
1 / arr
arr ** 0.5

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

In [ ]:
arr2 > arr

### Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8]

In [ ]:
arr[5:8] = 12
arr

In [ ]:
a = [i for i in range(10)]
a

In [ ]:
a[5:8] = [12, 12, 12]
a

In [ ]:
arr_slice = arr[5:8]
arr_slice

In [ ]:
arr_slice[1] = 12345
arr

In [ ]:
arr_slice[:] = 64
arr

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

In [ ]:
arr2d[2]

In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0, 2]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]

In [ ]:
old_values = arr3d[0].copy()
old_values

In [ ]:
arr3d[0] = 42
arr3d

In [ ]:
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

In [ ]:
x = arr3d[1]
x

In [ ]:
x[0]

#### Indexing with slices

In [ ]:
arr

In [ ]:
arr[1:6]

In [ ]:
arr2d

In [ ]:
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:2, 2:3]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:, 0]

In [ ]:
arr2d

In [ ]:
arr2d[:2, 1:] = 0
arr2d

### Boolean Indexing

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

In [ ]:
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[:4:3]

In [ ]:
data[np.array([False, False, False, False, False, False, True])]

In [ ]:
data[6]

In [ ]:
data

In [ ]:
test = np.array([True, False, True, False])
test

In [ ]:
data[:, test] #0, 3 열 선택

In [ ]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'
data[~(names == 'Bob')]

In [ ]:
cond = names == 'Bob'
data[~cond]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

### Fancy Indexing

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[4, 3, 0, 6]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

In [ ]:
arr[:, [1, 0]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
s = [(x, y) for x, y in zip([1, 5, 7, 2], [0, 3, 1, 2])]
s

In [ ]:
s = [arr[x, y] for x, y in zip([1, 5, 7, 2], [0, 3, 1, 2])]
s

In [ ]:
arr[[1, 5, 7, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr

In [ ]:
arr[:, [0, 3, 1, 2]]

### Transposing Arrays and Swapping Axes

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

In [ ]:
arr.T

In [ ]:
arr = np.random.randn(6, 3)
arr

In [ ]:
arr.T

In [ ]:
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr # (2, 2, 4)

In [ ]:
# p157
arr.transpose((0, 1, 2)) # (2, 2, 4)

In [ ]:
arr.transpose((0, 2, 1)) # , 축 1과 2를 바꾸기 (2, 4, 2)

In [ ]:
arr.transpose((1, 0, 2)) # (2, 2, 4)

In [ ]:
arr.transpose((1, 2, 0)) # (2, 4, 2)

In [ ]:
arr.transpose((2, 0, 1)) # (4, 2, 2)

In [ ]:
arr.transpose((2, 1, 0)) # (4, 2, 2)

In [ ]:
arr
arr.swapaxes(1, 2) #0, 1, 2 중의 저시한 두 개의 축을 교환

In [ ]:
arr
arr.swapaxes(2, 1) #0, 1, 2 중의 저시한 두 개의 축을 교환

In [ ]:
# 아래와 동일
arr.transpose((0, 2, 1))

## Universal Functions: Fast Element-Wise Array Functions

In [ ]:
arr = np.arange(10)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
pow(2.7183, 3)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x

In [ ]:
y

In [ ]:
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5
arr

In [ ]:
remainder, whole_part = np.modf(arr)

In [ ]:
remainder

In [ ]:
whole_part

In [ ]:
arr

In [ ]:
arr = np.abs(arr)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
arr

In [ ]:
np.sqrt(arr, arr)
arr

## Array-Oriented Programming with Arrays

In [ ]:
pts = np.arange(-5, 5)
pts

In [ ]:
xs, ys = np.meshgrid(pts, pts)
xs

In [ ]:
ys

In [ ]:
z = np.abs(np.add(xs, ys))
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of np.abs(np.add(xs, ys)) for a grid of values")
plt.plot()

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
points

In [ ]:
xs, ys = np.meshgrid(points, points)
xs

In [ ]:
ys

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.plot()
#plt.draw()

In [ ]:
z.shape

In [ ]:
import matplotlib.image as img
import matplotlib.pyplot as plt

fileName = "sample.png"
ndarray = img.imread(fileName)
plt.imshow(ndarray)
plt.show()

### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
cond

In [ ]:
result = [x if c else y for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr

In [ ]:
arr > 0

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

### Mathematical and Statistical Methods

In [ ]:
arr = np.random.randn(5, 4)
arr

In [ ]:
arr.mean()

In [ ]:
np.mean(arr)

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=0)

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.sum(axis=0)

In [ ]:
arr.sum(axis=1)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum()

In [ ]:
arr.cumsum(axis=0)

In [ ]:
arr.cumsum(axis=1)

In [ ]:
arr.cumprod(axis=1)

### Methods for Boolean Arrays

In [ ]:
arr = np.random.randn(100)
arr

In [ ]:
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools

In [ ]:
bools.any()

In [ ]:
bools.all()

* 2차원 배열에서 

In [ ]:
arr = np.random.randn(5, 4)
arr

In [ ]:
(arr>0).any(axis=0)

In [ ]:
arr[:, (arr>0).any(axis=0)] # 원소가 하나라도 양수인 열

In [ ]:
(arr<0).all(axis=1)

In [ ]:
arr[(arr<0).all(axis=1)] # 원소가 모두 음수인 행

### Sorting

In [ ]:
arr = np.random.randn(6)
arr

In [ ]:
arr.sort()
arr

In [ ]:
arr = np.random.randn(5, 3)
arr

In [ ]:
np.sort?

In [ ]:
np.sort(arr)

In [ ]:
arr

In [ ]:
np.sort(arr, axis=0)

In [ ]:
np.sort(arr, axis=1)

In [ ]:
np.sort(arr) # 기본이 axis=-1, 마지막 축으로 정렬

In [ ]:
np.sort?

In [ ]:
np.sort(arr, axis=None) #평탄화시킨 후 정렬

In [ ]:
arr.sort? #Sort an array in-place

In [ ]:
arr.sort(axis=0) #정렬 반영
arr

In [ ]:
arr

In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[:10]

In [ ]:
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and Other Set Logic

In [ ]:
names = np.array(['Joe', 'Will', 'Bob', 'Bob', 'Will', 'Joe', 'Joe'])
names

In [ ]:
np.unique(names)

In [ ]:
sorted(set(names))

In [ ]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6]) # x 원소가 y 원소에 포함되는지

## File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
np.save('some_array', arr) #*.npy

In [ ]:
!chcp 65001

In [ ]:
!dir some_array.npy

In [ ]:
np.load('some_array.npy')

In [ ]:
arr2 = np.arange(15)

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr2)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
del arch

In [ ]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr2)

In [ ]:
!del some_array.npy
!del array_archive.npz
!del arrays_compressed.npz

In [ ]:
# change code page
!chcp 65001

In [ ]:
!dir

## Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [ ]:
x

In [ ]:
y

In [ ]:
x.dot(y)

In [ ]:
np.dot(x, y)

In [ ]:
np.ones(3)

In [ ]:
np.ones((3, 1))

* 2차원 배열과 곱셉이 가능한 크기의 1차원 배열 간의 행렬 곱셈의 결과는 1차원 배열

In [ ]:
x

In [ ]:
x.dot(np.ones((3, 1)))

In [ ]:
np.ones(3)

In [ ]:
x.dot(np.ones(3))

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
x

In [ ]:
np.ones(3)

In [ ]:
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
X

In [ ]:
mat = X.T.dot(X)
mat

In [ ]:
inv(mat)

In [ ]:
mat.dot(inv(mat))

In [ ]:
q, r = qr(mat)
q

In [ ]:
r

## Pseudorandom Number Generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

In [ ]:
%timeit np.random.normal(size=N)

In [ ]:
np.random.seed(1234)
np.random.randn(10)

In [ ]:
np.random.seed(123)
np.random.randn(10)

In [ ]:
rng = np.random.RandomState(1234)
rng.randn(10)

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
walk

In [ ]:
np.random.seed(100)
steps = 100
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1 #0, 1중 난수 발생
    position += step
    walk.append(position)
walk

In [ ]:
plt.figure()

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
np.random.seed(12345)
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps) #0, 1중 난수 발생
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk[:20]

In [ ]:
walk.min()

In [ ]:
walk.max()

In [ ]:
np.array([False, False, True, False]).argmax()

In [ ]:
np.array([1, 2, 30, 5, 30]).argmax()

In [ ]:
(np.abs(walk) >= 10).argmax()

In [ ]:
(np.abs(walk) >= 10)[:10]

In [ ]:
np.argmax([1, 2, 5, 7, 9])

In [ ]:
np.argmax([1, 2, 5, 3, -1])

In [ ]:
(np.abs(walk) >= 13).argmax()

### Simulating Many Random Walks at Once

In [ ]:
np.random.seed(12345)
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
steps

In [ ]:
steps.shape

In [ ]:
walks = steps.cumsum(1)
walks

In [ ]:
walks.max() #원소의 최대 값

In [ ]:
walks.min() #원소의 최소 값

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

In [ ]:
len(hits30)

In [ ]:
hits30.sum() # Number that hit 30 or -30, 누적 합이 30 또는 -30 이상 되는 수

In [ ]:
a = np.arange(10).reshape(2,5)
a

In [ ]:
np.argmax(a, axis=0)

In [ ]:
np.argmax(a, axis=1)

In [ ]:
# 절대값이 30이 넘는 실험 행에서 누적 절대값이 30 이상이 되는 최소 횟수
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times 

In [ ]:
crossing_times.shape

In [ ]:
#절대값이 30이 넘는 실험 행에서 누적 절대값이 30 이상이 되는 평균 횟수
crossing_times.mean() 

In [ ]:
crossing_times[:10]

In [ ]:
steps = np.random.normal(loc=0, scale=0.25, size=(nwalks, nsteps))
steps

## Conclusion

In [ ]:
a = np.arange(72).reshape(6, 12)
a

In [ ]:
np.hsplit(a, 2)

In [ ]:
np.hsplit(a, 3)

In [ ]:
np.vsplit(a, 3)

In [ ]:
np.vsplit(a, 2)

In [ ]:
b = np.arange(1, 25).reshape(4, 6)
b

In [ ]:
r = np.vsplit(b, 2)
r